spec:
  name: devorbit-api
  region: blr
  services:
    - name: api
      source:
        repo:
          branch: main
          repo: harshareddy-bathala/devAtlas
          deploy_on_push: true
      source_dir: server
      dockerfile_path: server/Dockerfile
      http_port: 3001
      instance_count: 1
      instance_size_slug: apps-s-1vcpu-0.5gb
      routes:
        - path: /
      health_check:
        http_path: /api/health
        initial_delay_seconds: 10
        period_seconds: 30
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
      envs:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: "3001"
        - key: CORS_ORIGIN
          value: "${CORS_ORIGIN}"
        - key: FIREBASE_SERVICE_ACCOUNT
          value: "${FIREBASE_SERVICE_ACCOUNT}"
          type: SECRET
